definitions:
    AddTenorLmitRequestDto:
        properties:
            consumer_id:
                type: string
                x-go-name: ConsumerId
            limits:
                items:
                    $ref: '#/definitions/TenorLimitDto'
                type: array
                x-go-name: Limits
        type: object
        x-go-package: github.com/muhammadandikakurniawan/xyz_multifinance/src/module/consumer/usecase/consumer/dto
    RequestCreateNewConsumerDto:
        properties:
            date_of_birth:
                type: string
                x-go-name: DateOfBirth
            fullname:
                type: string
                x-go-name: Fullname
            ktp_base64:
                type: string
                x-go-name: KtpImageBase64
            legalname:
                type: string
                x-go-name: Legalname
            nik:
                type: string
                x-go-name: NIK
            place_of_birth:
                type: string
                x-go-name: PlaceOfBirth
            salary:
                format: double
                type: number
                x-go-name: Salary
            selfie_base64:
                type: string
                x-go-name: SelfeBase64
        type: object
        x-go-package: github.com/muhammadandikakurniawan/xyz_multifinance/src/module/consumer/usecase/consumer/dto
    RequestLoanDto:
        properties:
            admin_fee:
                format: double
                type: number
                x-go-name: AdminFee
            asset_name:
                type: string
                x-go-name: AssetName
            consumer_id:
                type: string
                x-go-name: ConsumerId
            contract_number:
                type: string
                x-go-name: ContractNumber
            id:
                format: int64
                type: integer
                x-go-name: Id
            installment:
                format: double
                type: number
                x-go-name: Installment
            interest:
                format: double
                type: number
                x-go-name: Interest
            is_approved:
                type: boolean
                x-go-name: IsApproved
            otr:
                format: double
                type: number
                x-go-name: OTR
        type: object
        x-go-package: github.com/muhammadandikakurniawan/xyz_multifinance/src/module/consumer/usecase/consumer/dto
    TenorLimitDto:
        properties:
            consumer_id:
                type: string
                x-go-name: ConsumerId
            month:
                format: int64
                type: integer
                x-go-name: Month
            value:
                format: double
                type: number
                x-go-name: Value
        type: object
        x-go-package: github.com/muhammadandikakurniawan/xyz_multifinance/src/module/consumer/usecase/consumer/dto
info: {}
paths:
    /consumer/register:
        post:
            description: Register consumer
            operationId: registerConsumer
            parameters:
                - in: body
                  name: Body
                  schema:
                    $ref: '#/definitions/RequestCreateNewConsumerDto'
            produces:
                - application/json
            responses:
                "200":
                    description: register response
            tags:
                - consumer
    /consumer/request-loan:
        post:
            description: request loan
            operationId: requestLoan
            parameters:
                - in: body
                  name: Body
                  schema:
                    $ref: '#/definitions/RequestLoanDto'
            produces:
                - application/json
            responses:
                "200":
                    description: request loan
            tags:
                - consumer
    /consumer/tenor-limit:
        post:
            description: Add tenor limit for consumer
            operationId: addTenorLimit
            parameters:
                - in: body
                  name: Body
                  schema:
                    $ref: '#/definitions/AddTenorLmitRequestDto'
            produces:
                - application/json
            responses:
                "200":
                    description: add consumer tenor limit
            tags:
                - consumer
swagger: "2.0"
