// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/go-playground/validator/v10"
	"github.com/muhammadandikakurniawan/xyz_multifinance/src/module/consumer/config"
	"github.com/muhammadandikakurniawan/xyz_multifinance/src/module/consumer/infrastructure/filestorage"
	"github.com/muhammadandikakurniawan/xyz_multifinance/src/module/consumer/infrastructure/repository/mysql"
	"github.com/muhammadandikakurniawan/xyz_multifinance/src/module/consumer/usecase/consumer"
	"github.com/muhammadandikakurniawan/xyz_multifinance/src/shared/database"
	"github.com/muhammadandikakurniawan/xyz_multifinance/src/shared/minio"
	"github.com/muhammadandikakurniawan/xyz_multifinance/src/shared/moduleregistry"
	"gorm.io/gorm"
)

// Injectors from container.go:

func InitializeDependencyContainer() Container {
	moduleRegistry := moduleregistry.NewModuleRegistry()
	appConfig := config.LoadByEnv()
	validate := validator.New()
	db := NewMysqlDb(appConfig)
	consumerRepository := mysql.NewConsumerRepository(db)
	minio := NewMinioClient(appConfig)
	fileStorage := filestorage.NewFileBucketClient(minio)
	consumerUsecase := consumer.NewConsumerUsecase(appConfig, validate, consumerRepository, fileStorage)
	container := newContainer(moduleRegistry, appConfig, consumerUsecase)
	return container
}

// container.go:

type Container struct {
	AppConfig       config.AppConfig
	ConsumerUsecase consumer.ConsumerUsecase
	moduleRegistry  moduleregistry.ModuleRegistry
}

func NewMysqlDb(cfg config.AppConfig) *gorm.DB {
	db, err := database.NewMysql(cfg.DatabaseMysqlConnectionString, gorm.Config{})
	if err != nil {
		panic(err)
	}
	return db
}

func NewMinioClient(cfg config.AppConfig) minio.Minio {
	client, err := minio.NewMinio(cfg.MinioConfig)
	if err != nil {
		panic(err)
	}
	return client
}

func newContainer(
	moduleRegistry moduleregistry.ModuleRegistry,
	AppConfig config.AppConfig,
	ConsumerUsecase consumer.ConsumerUsecase,
) Container {
	c := Container{
		moduleRegistry:  moduleRegistry,
		AppConfig:       AppConfig,
		ConsumerUsecase: ConsumerUsecase,
	}
	return c
}
